title: Venkat Akhil Ankem
description: Ph.D. Candidate in Industrial Engineering | Operations Research | Large-Scale Optimization | Mining, Transportation, and Industrial Applications
theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg
show_downloads: false