title: Venkat Akhil Ankem
description: Ph.D. Candidate in Operations Research | Large-Scale MILP Optimization & Applied ML | Polytechnique Montréal · GERAD
theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg
show_downloads: false
